# список моделей
curl -H "Authorization: Bearer RUNPOD_API_KEY" \
  "https://api.runpod.ai/v2/0v4jhl6l3fggu2/openai/v1/models"

# простой чат
curl -s -X POST "https://api.runpod.ai/v2/0v4jhl6l3fggu2/openai/v1/chat/completions" \
  -H "Authorization: Bearer RUNPOD_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"model":"openai/gpt-oss-20b","messages":[{"role":"user","content":"ping"}],"temperature":0}'
